### ISSUE TITLE
Page load hangs: emoji.css, favicon.ico

### ISSUE THREAD

**Issue by billimarie** [WomenWhoCode/womenwhocode.github.io#16]
Hi! I'm a docs nerd new to the WWC website repo and would love to help with the contributor's resource site.

The page takes up to a minute to load. Permission to kill/fix these? (emoji.css, favicon.ico)

![screen shot 2016-07-28 at 7 54 07 pm](https://cloud.githubusercontent.com/assets/6895471/17236360/5b1945c0-54fd-11e6-9653-ed156c98df10.png)

**Comment by jig08** [comment]
@billimarie Feel free to send a PR with a fix :)

**Comment by jig08** [comment]
Thanks @billimarie
