### ISSUE TITLE
list github learning resources for github beginners

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/womenwhocode.github.io#4]

**Comment by rocketpastsix** [comment]
Do you need some help on this? Would be glad to lend a hand and help out.

**Comment by kmolo** [comment]
There are some links listed here that may be useful to the implementer:

https://github.com/WomenWhoCode/guidelines-resources/blob/master/learn_to_program.md#git

**Comment by zassmin** [comment]
closing for now, no longer relevant
